### ISSUE TITLE
Server: Need to only access via https only

### ISSUE THREAD

**Issue by Drewski6** [svvoii/ft_transcendence#33]
- Similar to inception how we needed to only allow access via https or reroute a http request to the https port, we need to do the same for security reasons.
- Our application uses a lot of api calls which uses json data. this is plain text and needs to be encrypted with the https protocol
- using postman, I can see that http only works right now, https requests hang and eventually time out

**Comment by svvoii** [comment]
Note: 
I will take care of redirecting HTTP requests to HTTPS. 
This might include adding arguments or configurations to the server either before or at the time of spinning it up.
Setting up nginx as reverse proxy might be another option.
